CREATE OR REPLACE VIEW dwh.vw_dim_sale_order AS
SELECT
id as order_id
,name
,project_title
,state
,date_order::date as order_date
,partner_id
,note

,discount_type
,discount_rate
,amount_discount
,amount_untaxed
,amount_tax
,amount_total

,state_devis
,zip_client
,region
,ville_client
,region_client
,ref_intervention
,source
,relance
,note_relance
,date_relance
,responsable_intervention
,remarque
,status_pose

--,campaign_id
--,source_id
--,medium_id
--,access_token
--,message_main_attachment_id
--,origin
--,client_order_ref
--,reference
--,validity_date
--,require_signature
--,require_payment
--,create_date
--,user_id
--,partner_invoice_id
--,partner_shipping_id
--,pricelist_id
--,analytic_account_id
--,invoice_status
--,currency_rate
--,payment_term_id
--,fiscal_position_id
--,company_id
--,team_id
--,signed_by
--,signed_on
--,commitment_date
--,create_uid
--,write_uid
--,write_date
--,sale_order_template_id
--,incoterm
--,picking_policy
--,warehouse_id
--,procurement_group_id
--,effective_date
--,style
--,opportunity_id
--,carrier_id
--,delivery_message
--,delivery_rating_success
--,recompute_delivery_price
--,planning_id
--,type_devis
--,code_promo_program_id
--,force_invoiced
--,amount_words
--,dispatch_type
--,hide_net_price
--,old_state
--,information
--,atelier_id
--,decharge
--,invoice_id
--,etl_loaded_at
--,etl_batch_id
FROM dwh.dim_sale_order;